#!/bin/bash

# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# DENO
export DENO_INSTALL="/home/mawathilde/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"

# Sub bashrc
source $HOME/.bashrc.d/prompt
source $HOME/.bashrc.d/history
source $HOME/.bashrc.d/aliases
source $HOME/.bashrc.d/completions