#!/bin/bash

# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

export DENO_INSTALL="/home/$USER/.deno"

# Additional paths
export PATH="$DENO_INSTALL/bin:$PATH"
export PATH=$PATH:/usr/local/go/bin

if [ -f "$HOME/.cargo/env" ]; then
    . "$HOME/.cargo/env"
fi

source $HOME/.sdkman/bin/sdkman-init.sh

# Sub bashrc
source $HOME/.bashrc.d/prompt
source $HOME/.bashrc.d/history
source $HOME/.bashrc.d/aliases
source $HOME/.bashrc.d/completions